baseURL = 'https://example.org/'
languageCode = 'es'
title = 'Salvador Romero'
theme = 'ananke'



DefaultContentLanguage = "es"

[menu]
  [[menu.main]]
	identifier = "about"
	name = "Sobre mi"
	title = "Sobre mi"
	url = "/about/"
	weight = 0
  [[menu.main]]
	identifier = "posts"
	name = "Proyectos"
	title = "Proyectos"
	url = "/posts/"
	weight = 0