baseURL = 'https://example.org/'
languageCode = 'es'
title = 'Salvador Romero'
theme = 'ananke'


#SectionPagesMenu = "main"
DefaultContentLanguage = "es"

[menu]
  [[menu.main]]
	#identifier = "about"
	name = "Sobre mi"
	title = "Sobre mi"
	url = "/about/"
	weight = 1
  [[menu.main]]
	#identifier = "posts"
	name = "Proyectos"
	title = "Proyectos"
	url = "/posts/"
	weight = 2


[params]
  linkedin = "https://www.linkedin.com/in/salvadorromerodelaroca/"  
  github = "https://github.com/SalvadorRdR"
  recent_posts_number = 3
